class ReceitaLaboratorio:
    def __init__(self, page, solicitante, ordem_de_compra):
        self.page = page
        self.solicitante = solicitante
        self.ordem_de_compra = ordem_de_compra


    def digitar_pedido(self):
        self.page.get_by_role("textbox", name="Solicitante", exact=True).fill(str(self.solicitante))
        self.page.get_by_role("textbox", name="Ordem de compra", exact=True).fill(str(self.ordem_de_compra))
        self.page.locator("#longeEsfericoOD").click()
        self.page.locator("#longeEsfericoOD").fill("1")
        self.page.locator("#longeEsfericoOD").press("Tab")
        self.page.locator("#longeCilindricoOD").fill("-1")
        self.page.locator("#longeCilindricoOD").press("Tab")
        self.page.locator("#longeEixoOD").fill("90")
        self.page.locator("#longeEixoOD").press("Tab")
        self.page.locator("#adicaoOD").fill("1")
        self.page.locator("#adicaoOD").press("Tab")
        self.page.locator("#DataList_AdicaoOD").press("Tab")
        self.page.locator("#longeEsfericoOD_Perto").press("Tab")
        self.page.locator("#dnpOD").fill("33")
        self.page.locator("#dnpOD").press("Tab")
        self.page.locator("#alturaOD").fill("23")
        self.page.locator("#alturaOD").press("Tab")
        self.page.locator("#BaseOD").press("Tab")
        self.page.locator("#descentracaoOD").press("Tab")
        self.page.locator("#longeEsfericoOE").fill("1")
        self.page.locator("#longeEsfericoOE").press("Tab")
        self.page.locator("#longeCilindricoOE").fill("-1")
        self.page.locator("#longeCilindricoOE").press("Tab")
        self.page.locator("#longeEixoOE").fill("90")
        self.page.locator("#longeEixoOE").press("Tab")
        self.page.locator("#adicaoOE").fill("1")
        self.page.locator("#adicaoOE").press("Tab")
        self.page.locator("#DataList_AdicaoOE").press("Tab")
        self.page.locator("#longeEsfericoOE_Perto").press("Tab")
        self.page.locator("#dnpOE").fill("33")
        self.page.locator("#dnpOE").press("Tab")
        self.page.locator("#alturaOE").fill("23")
        self.page.locator("#alturaOE").press("Tab")
        self.page.locator("#BaseOE").press("Tab")
        self.page.locator("#descentracaoOE").press("Tab")
        self.page.wait_for_timeout(3000)  # Espera 3 segundos
        self.page.get_by_role("option", name="Multifocal").click()
        self.page.get_by_role("combobox", name="Multifocal").press("Tab")
        self.page.wait_for_timeout(3000)  # Espera 3 segundos
        self.page.locator("#codigoOD").fill("41312")
        self.page.locator("#codigoOD").press("Tab")
        self.page.get_by_role("link", name="INCLUIR/ATUALIZAR PRODUTO").click()
        self.page.wait_for_timeout(3000)
        self.page.get_by_role("img", name="Modelo").first.click()
        self.page.locator(".col-6.col-md-2.PaddingMenor").first.click()
        self.page.get_by_role("textbox", name="MVA").fill("45")
        self.page.get_by_role("textbox", name="MVA").press("Tab")
        self.page.get_by_role("textbox", name="MHA").fill("50")
        self.page.get_by_role("textbox", name="MHA").press("Tab")
        self.page.get_by_role("textbox", name="DMA").fill("50")
        self.page.get_by_role("textbox", name="DMA").press("Tab")
        self.page.get_by_role("textbox", name="Ponte").fill("18")
        self.page.get_by_role("textbox", name="Ponte").press("Tab")
        self.page.get_by_role("textbox", name="DPA").press("Tab")
        self.page.get_by_role("textbox", name="Diâmetro").press("Tab")
        self.page.wait_for_timeout(3000)
        self.page.get_by_role("option", name="ACETATO", exact=True).click()
        self.page.wait_for_timeout(3000)
        self.page.locator(".col-12 > .BoxSwitch > .switch__container > label").first.click()
        self.page.get_by_role("link", name="ENVIAR PEDIDO").click()
        self.page.wait_for_timeout(3000)
        self.page.get_by_role("button", name="FECHAMENTO").click()
        self.page.wait_for_timeout(3000)
        self.page.get_by_text("Fechar", exact=True).click()